<Project>
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>Ubytec</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<EnableDocFxOnBuild>true</EnableDocFxOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup>
		<EnableDocFxOnBuild Condition="'$(EnableDocFxOnBuild)'==''">false</EnableDocFxOnBuild>
	</PropertyGroup>
</Project>
