name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: DocFX Publish
        # You may pin to the exact commit or the version.
        # uses: frankhaugen/frank-docfx-publish@ae488e9172294f60ab21755503bd8f07ee5fce0c
      uses: frankhaugen/frank-docfx-publish@1.0
      with:
        dotnet-version: 9.0.x
        # Path to the docfx.json file
        docfxJson: Wiki/docfx.json
        # Directory to publish documentation to
        publishDir: Wiki/_site
          
      
