name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.4.2
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
        dotnet-version: 9.0.* # optional
        # Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.
          
    - name: docfx-action
      # You may pin to the exact commit or the version.
      # uses: nikeee/docfx-action@b9c2cf92e3b4aa06878a1410833a8828b4bdcd26
      uses: nikeee/docfx-action@v1.0.0
          

          
      
